[workspace]
name = "scanpy-scale"
channels = ["https://prefix.dev/almost-conductor", "conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.12,<3.14"
scanpy = "*"
anndata = "*"
h5py = "*"
numpy = "*"
pandas = "*"
scipy = "*"
denet = "*"

[pypi-dependencies]
obkit = ">=0.0.3"
